apiVersion: v2
name: flink-poc
description: Chart for deploying my flink-poc

type: application

version: 1.0.0
appVersion: 1.0.0

maintainers:
  - email: henkvdyk1@gmail.com
    name: Henk van Dyk

# application dependencies
dependencies:
  - name: schema-registry ##used for schema reg and kafka stack
    repository: https://charts.bitnami.com/bitnami
    version: 9.0.1