apiVersion: v1
kind: Service
metadata:
  name: flink-example-1-jobmanager
  namespace: flink
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: flink-example-jobmanager-1
    component: jobmanager